// ================================================================
// Sprint D-6 — Weekly Performance Report PDF template (6 pages A4).
//
// Pages (in order):
//   1. Cover            — full-bleed mesh + display-xl + date range
//   2. Executive Summary — narrative + 4 KPI tiles + 3 insights
//   3. Revenue           — Aurora chart 7d + stats + top 5 customers
//   4. Cash & Margin     — flow stream + margin sparkline + top 5 expenses
//   5. Customer & Tax    — donut concentration + tax timeline
//   6. Action Items      — 3 actions + closing + Zyrix CTA
//
// "Foundation Week" path: if merchantNew is true, ship a single
// welcome page instead of the 6-page structure (data would be too
// sparse to be meaningful).
//
// Pure HTML — caller passes through D-2.5 pdfRenderer.ts to PDF.
// ================================================================
import { htmlShell, footer, formatDate, coverBackground } from './_layout';
import {
  auroraChart, liquidKpiCard, pulseSparkline,
  holographicDonut, flowStream, aiInsightCard, constellationKpiGrid
} from './charts';
import { paletteOf, Theme, Locale, Tone, toneColor } from '../palette';
import { esc } from '../escape';

// ─── Localized chrome labels (kept inline; mirrors other templates) ──

const STR = {
  weeklyTitle:    { tr: 'Haftalık Performans',          en: 'Weekly Performance',         ar: 'الأداء الأسبوعي' },
  brief:          { tr: 'Bu Hafta Özetle',              en: 'This Week in Summary',       ar: 'هذا الأسبوع باختصار' },
  insightsLabel:  { tr: 'Verilerden çıkardığımız 3 önemli içgörü:', en: 'Three insights from your data:', ar: 'ثلاث رؤى مهمة من بياناتك:' },
  revenueDive:    { tr: 'Gelir Analizi',                en: 'Revenue Deep-Dive',          ar: 'تحليل الإيرادات' },
  cashMargin:     { tr: 'Nakit ve Marj',                en: 'Cash & Margin',              ar: 'النقد والهامش' },
  customerTax:    { tr: 'Müşteri ve Vergi',             en: 'Customer & Tax',             ar: 'العملاء والضرائب' },
  actions:        { tr: 'Önerilen Aksiyonlar',          en: 'Recommended Actions',        ar: 'الإجراءات الموصى بها' },
  closing:        { tr: 'Hafta seninle güzel olsun.',    en: 'Have a great week.',         ar: 'أتمنى لك أسبوعاً موفقاً' },
  generatedBy:    { tr: 'AI Co-Pilot tarafından oluşturuldu', en: 'Generated by AI Co-Pilot', ar: 'تم إنشاؤه بواسطة المساعد الذكي' },
  dateRange:      { tr: 'Tarih Aralığı',                en: 'Date Range',                 ar: 'النطاق الزمني' },

  // KPI labels
  mrr:            { tr: 'MRR',                          en: 'MRR',                        ar: 'الإيرادات الشهرية' },
  netCash:        { tr: 'Net Nakit',                    en: 'Net Cash',                   ar: 'صافي النقد' },
  margin:         { tr: 'Brüt Marj',                    en: 'Gross Margin',               ar: 'الهامش الإجمالي' },
  runway:         { tr: 'Nakit Ömrü',                   en: 'Cash Runway',                ar: 'عمر النقد' },

  // Stats labels
  totalRevenue:   { tr: 'Toplam Gelir',                 en: 'Total Revenue',              ar: 'إجمالي الإيرادات' },
  avgDaily:       { tr: 'Günlük Ortalama',              en: 'Daily Average',              ar: 'المتوسط اليومي' },
  bestDay:        { tr: 'En İyi Gün',                   en: 'Best Day',                   ar: 'أفضل يوم' },
  worstDay:       { tr: 'En Düşük Gün',                 en: 'Lowest Day',                 ar: 'أدنى يوم' },
  vsLastWeek:     { tr: 'Geçen Haftaya Karşı',          en: 'vs Last Week',               ar: 'مقارنة بالأسبوع الماضي' },
  topCustomers:   { tr: 'Önde Gelen Müşteriler',        en: 'Top Customers',              ar: 'كبار العملاء' },
  inflows:        { tr: 'İçeri Akış',                   en: 'Inflows',                    ar: 'التدفقات الداخلة' },
  outflows:       { tr: 'Dışarı Akış',                  en: 'Outflows',                   ar: 'التدفقات الخارجة' },
  netFlow:        { tr: 'Net Akış',                     en: 'Net Flow',                   ar: 'صافي التدفق' },
  topExpenses:    { tr: 'En Yüksek Giderler',           en: 'Top Expenses',               ar: 'أعلى المصروفات' },
  concentration:  { tr: 'Müşteri Yoğunluğu',            en: 'Customer Concentration',     ar: 'تركيز العملاء' },
  concentrationRisk: { tr: 'Yoğunluk Riski',            en: 'Concentration Risk',         ar: 'مخاطر التركيز' },
  upcomingTax:    { tr: 'Yaklaşan Vergi Yükümlülükleri', en: 'Upcoming Tax Obligations',  ar: 'الالتزامات الضريبية القادمة' },
  noTax:          { tr: 'Önümüzdeki hafta için kayıtlı vergi yok.', en: 'No taxes recorded for the coming week.', ar: 'لا توجد ضرائب مسجلة للأسبوع القادم.' },
  noInsights:     { tr: 'Bu hafta için içgörü kaydedilmedi.', en: 'No insights recorded this week.', ar: 'لم تُسجَّل رؤى لهذا الأسبوع.' },
  noExpenses:     { tr: 'Bu haftada gider kaydı yok.',  en: 'No expenses recorded this week.', ar: 'لا توجد مصروفات هذا الأسبوع.' },
  noCustomers:    { tr: 'Bu haftada müşteri geliri yok.', en: 'No customer revenue this week.', ar: 'لا إيرادات عملاء هذا الأسبوع.' },

  // Severity badges
  CRITICAL:       { tr: 'KRİTİK',                       en: 'CRITICAL',                   ar: 'حرج' },
  ATTENTION:      { tr: 'DİKKAT',                       en: 'ATTENTION',                  ar: 'تنبيه' },
  OPPORTUNITY:    { tr: 'FIRSAT',                       en: 'OPPORTUNITY',                ar: 'فرصة' },

  // Foundation week
  foundationTitle: { tr: 'İlk Haftana Hoş Geldin',      en: 'Welcome to Your First Week', ar: 'مرحبًا بك في أسبوعك الأول' },
  foundationBody:  {
    tr: 'Henüz bir tam haftalık veri toplanmadı. Faturalarını oluştur, müşterilerini ekle, banka hesabını bağla — gelecek pazar günü ilk gerçek raporun hazır olacak.',
    en: 'A full week of data hasn\'t accumulated yet. Create invoices, add customers, link your bank — your first full report arrives next Sunday.',
    ar: 'لم تتراكم بيانات أسبوع كامل بعد. أنشئ الفواتير، أضف العملاء، وأربط حسابك المصرفي — سيصلك أول تقرير كامل يوم الأحد القادم.'
  }
} as const;

const T = (key: keyof typeof STR, locale: Locale): string => {
  const v: any = STR[key];
  return v?.[locale] || v?.tr || String(key);
};

// ─── Public data shape ──────────────────────────────────────────

export interface WeeklyKpi { value: number; delta: number; deltaPct: number; }
export interface WeeklyInsight {
  type:      'CRITICAL' | 'ATTENTION' | 'OPPORTUNITY';
  title:     string;
  body:      string;
  ctaLabel?: string;
}
export interface WeeklySnapshotForTemplate {
  weekStart:   string;
  weekEnd:     string;
  currency:    string;
  merchantNew: boolean;
  kpis: { mrr: WeeklyKpi; netCash: WeeklyKpi; margin: WeeklyKpi; runway: WeeklyKpi };
  revenue: {
    total: number; avgDaily: number;
    bestDay:  { date: string; amount: number } | null;
    worstDay: { date: string; amount: number } | null;
    dailySeries: Array<{ date: string; amount: number }>;
    priorSeries: Array<{ date: string; amount: number }>;
    topCustomers: Array<{ name: string; amount: number }>;
  };
  cash: {
    inflowTotal: number; outflowTotal: number; netFlow: number;
    topExpenses: Array<{ category: string; amount: number; date: string }>;
  };
  customers: {
    totalCount: number;
    concentration: Array<{ name: string; amount: number; pct: number }>;
    topCustomerShare: number;
  };
  tax: { upcoming: Array<{ title: string; amount: number; dueDate: string }> };
}

export interface WeeklyReportTemplateData {
  weekStart:    Date;
  weekEnd:      Date;            // inclusive Sunday
  merchantName: string;
  narrative:    string;
  snapshot:     WeeklySnapshotForTemplate;
  insights:     WeeklyInsight[];
}

export function renderWeeklyReportTemplate(args: {
  data:   WeeklyReportTemplateData;
  theme:  Theme;
  locale: Locale;
}): string {
  const { data, theme, locale } = args;
  const pal = paletteOf(theme);
  const sym = data.snapshot.currency === 'TRY' ? '₺' : data.snapshot.currency === 'SAR' ? 'SAR ' : '';
  const fmtCur = (n: number): string => `${sym}${Math.round(n).toLocaleString()}`;
  const fmtPct = (n: number): string => `${n >= 0 ? '+' : ''}${n.toFixed(1)}%`;

  // Foundation Week — single page when there's <7d of data.
  if (data.snapshot.merchantNew) {
    return htmlShell({
      title:  `${T('weeklyTitle', locale)} — ${data.merchantName}`,
      theme, locale,
      body: renderFoundationPage(data, theme, locale),
      extraStyle: SHARED_CSS(pal)
    });
  }

  const cover    = renderCoverPage(data, locale);
  const summary  = renderSummaryPage({ data, theme, locale, fmtCur, fmtPct });
  const revenue  = renderRevenuePage({ data, theme, locale, fmtCur, fmtPct });
  const cash     = renderCashPage   ({ data, theme, locale, fmtCur });
  const custTax  = renderCustomerTaxPage({ data, theme, locale, fmtCur });
  const actions  = renderActionsPage({ data, theme, locale });

  const body = [cover, summary, revenue, cash, custTax, actions].filter(Boolean).join('');

  return htmlShell({
    title:  `${T('weeklyTitle', locale)} — ${data.merchantName} — ${formatDate(data.weekStart, locale)}–${formatDate(data.weekEnd, locale)}`,
    theme, locale,
    body,
    extraStyle: SHARED_CSS(pal)
  });
}

// ─── Shared CSS for cover + section pages ───────────────────────

const SHARED_CSS = (pal: any) => `
  .cover-page {
    position: relative;
    height: 265mm;
    overflow: hidden;
    border-radius: 6pt;
    page-break-after: always;
    background: #0A0E27;
    color: #F8FAFC;
  }
  .section-page {
    page-break-before: always;
    padding-top: 8pt;
  }
  .section-title-row {
    display: flex; align-items: flex-start; justify-content: space-between;
    padding-bottom: 10pt; border-bottom: 1px solid ${pal.border};
    margin-bottom: 16pt;
  }
  .stat-strip {
    display: grid; grid-template-columns: repeat(4, 1fr); gap: 8pt;
    margin: 12pt 0 16pt;
  }
  .stat-cell {
    background: ${pal.surface};
    border: 1px solid ${pal.border};
    border-radius: 10pt;
    padding: 10pt 12pt;
  }
  .stat-cell .lbl {
    font-size: 8pt; font-weight: 700; color: ${pal.textFaint};
    letter-spacing: 0.06em; text-transform: uppercase;
  }
  .stat-cell .val {
    font-size: 14pt; font-weight: 700; color: ${pal.textPrimary};
    letter-spacing: -0.01em; margin-top: 4pt;
  }
  .narrative-block {
    background: ${pal.surface};
    border: 1px solid ${pal.border};
    border-radius: 10pt;
    padding: 14pt 16pt;
    font-size: 11pt;
    line-height: 1.7;
    color: ${pal.textPrimary};
    margin-bottom: 16pt;
  }
  table.zyrix-table {
    width: 100%; border-collapse: collapse;
    font-size: 10pt;
  }
  table.zyrix-table th {
    text-align: left; font-weight: 700; font-size: 8pt;
    color: ${pal.textFaint}; text-transform: uppercase; letter-spacing: 0.06em;
    padding: 6pt 8pt; border-bottom: 1px solid ${pal.border};
  }
  table.zyrix-table td {
    padding: 8pt; border-bottom: 1px solid ${pal.border};
    color: ${pal.textPrimary};
  }
`;

// ─── Pages ──────────────────────────────────────────────────────

function renderCoverPage(data: WeeklyReportTemplateData, locale: Locale): string {
  return `
    <div class="cover-page">
      ${coverBackground()}
      <div style="position: relative; z-index: 1; padding: 32pt; height: 100%;
                  display: flex; flex-direction: column; justify-content: space-between;">
        <div>
          <div style="display: inline-flex; align-items: center; gap: 6pt;
                      padding: 6pt 12pt;
                      background: rgba(0, 217, 255, 0.10);
                      border: 1px solid rgba(0, 217, 255, 0.40);
                      border-radius: 99pt;
                      color: #5DFAFF;
                      font-size: 8pt; font-weight: 700; letter-spacing: 0.10em;
                      text-transform: uppercase;">
            <span style="display: inline-block; width: 5pt; height: 5pt; border-radius: 50%;
                         background: #5DFAFF; box-shadow: 0 0 4pt #00D9FF;"></span>
            Zyrix FinSuite · AI Co-Pilot
          </div>
          <div style="margin-top: 24pt; font-size: 44pt; font-weight: 700; line-height: 1.0;
                      letter-spacing: -0.03em;">${esc(T('weeklyTitle', locale))}</div>
          <div style="margin-top: 12pt; font-size: 14pt; color: #CBD5E1; font-weight: 500;">
            ${esc(data.merchantName)}
          </div>
          <div style="margin-top: 36pt;">
            <div style="font-size: 9pt; color: #64748B; text-transform: uppercase; letter-spacing: 0.10em; font-weight: 700;">
              ${esc(T('dateRange', locale))}
            </div>
            <div style="margin-top: 4pt; font-size: 18pt; color: #F8FAFC; font-weight: 600;">
              ${esc(formatDate(data.weekStart, locale))} — ${esc(formatDate(data.weekEnd, locale))}
            </div>
          </div>
        </div>
        <div style="display: flex; align-items: center; justify-content: space-between;">
          <div style="font-size: 14pt; font-weight: 700; color: #F8FAFC;
                      text-shadow: 0 0 8pt rgba(0, 217, 255, 0.5);">
            Zyrix <span style="color: #00D9FF;">FinSuite</span>
          </div>
          <div style="font-size: 8pt; color: #64748B; letter-spacing: 0.06em;">
            ${esc(T('generatedBy', locale))}
          </div>
        </div>
      </div>
    </div>
  `;
}

function renderSummaryPage(args: {
  data: WeeklyReportTemplateData; theme: Theme; locale: Locale;
  fmtCur: (n: number) => string; fmtPct: (n: number) => string;
}): string {
  const { data, theme, locale, fmtCur, fmtPct } = args;
  const pal = paletteOf(theme);
  const k = data.snapshot.kpis;

  const kpis = [
    { label: T('mrr', locale),     value: k.mrr.value,     tone: 'cyan'    as Tone, format: fmtCur, delta: k.mrr.deltaPct },
    { label: T('netCash', locale), value: k.netCash.value, tone: 'mint'    as Tone, format: fmtCur, delta: k.netCash.deltaPct },
    { label: T('margin', locale),  value: k.margin.value,  tone: 'violet'  as Tone, format: (n: number) => `${n.toFixed(1)}%`, delta: k.margin.deltaPct },
    { label: T('runway', locale),  value: k.runway.value,  tone: 'amber'   as Tone, format: (n: number) => `${Math.round(n)}d`, delta: k.runway.deltaPct }
  ];

  const insightsHtml = data.insights.length > 0
    ? data.insights.slice(0, 3).map((i) => `
        <div style="margin-bottom: 8pt;">
          ${aiInsightCard({
            severity:    i.type.toLowerCase() as any,
            title:       i.title,
            description: i.body,
            actionLabel: i.ctaLabel,
            badgeText:   T(i.type, locale),
            theme
          })}
        </div>`).join('')
    : `<div class="card" style="text-align: center; padding: 24pt; color: ${pal.textFaint}; font-size: 10pt;">${esc(T('noInsights', locale))}</div>`;

  return `
    <div class="section-page">
      <div class="section-title-row">
        <div>
          <div class="t-caption" style="color: ${pal.textFaint};">${esc(T('weeklyTitle', locale))}</div>
          <div class="t-display-md" style="margin-top: 4pt;">${esc(T('brief', locale))}</div>
        </div>
        <div style="text-align: ${locale === 'ar' ? 'left' : 'right'};">
          <div class="t-caption" style="color: ${pal.textFaint};">${esc(T('dateRange', locale))}</div>
          <div class="t-heading-md t-dim" style="margin-top: 4pt;">
            ${esc(formatDate(data.weekStart, locale))} — ${esc(formatDate(data.weekEnd, locale))}
          </div>
        </div>
      </div>

      <div class="narrative-block">${esc(data.narrative)}</div>

      <div class="page-break-avoid mb-4">
        ${constellationKpiGrid({ kpis, theme })}
      </div>

      <div class="t-caption mb-2" style="color: ${pal.textFaint};">${esc(T('insightsLabel', locale))}</div>
      <div class="page-break-avoid">${insightsHtml}</div>

      ${footer({ merchantName: data.merchantName, generatedAt: new Date(), locale })}
    </div>
  `;
}

function renderRevenuePage(args: {
  data: WeeklyReportTemplateData; theme: Theme; locale: Locale;
  fmtCur: (n: number) => string; fmtPct: (n: number) => string;
}): string {
  const { data, theme, locale, fmtCur, fmtPct } = args;
  const pal = paletteOf(theme);
  const r = data.snapshot.revenue;
  const k = data.snapshot.kpis;

  const series = r.dailySeries.map((d) => ({ x: d.date.slice(5), y: d.amount }));

  const top = r.topCustomers.slice(0, 5);
  const topTotal = top.reduce((s, c) => s + c.amount, 0);
  const customerRows = top.length > 0
    ? top.map((c) => {
        const pct = topTotal > 0 ? (c.amount / topTotal) * 100 : 0;
        return `
          <tr>
            <td>${esc(c.name)}</td>
            <td style="text-align: right; font-weight: 700;">${esc(fmtCur(c.amount))}</td>
            <td style="text-align: right; color: ${pal.textFaint};">${pct.toFixed(0)}%</td>
            <td style="width: 40%;">
              <div style="height: 6pt; background: ${pal.border}; border-radius: 3pt;">
                <div style="height: 100%; width: ${pct.toFixed(0)}%; background: ${toneColor('cyan')}; border-radius: 3pt;"></div>
              </div>
            </td>
          </tr>`;
      }).join('')
    : `<tr><td colspan="4" style="text-align: center; color: ${pal.textFaint}; padding: 16pt;">${esc(T('noCustomers', locale))}</td></tr>`;

  return `
    <div class="section-page">
      <div class="section-title-row">
        <div>
          <div class="t-caption" style="color: ${pal.textFaint};">${esc(T('weeklyTitle', locale))}</div>
          <div class="t-display-md" style="margin-top: 4pt;">${esc(T('revenueDive', locale))}</div>
        </div>
      </div>

      <div class="page-break-avoid" style="margin-bottom: 16pt;">
        ${auroraChart({ data: series, tone: 'cyan', width: 520, height: 200, theme })}
      </div>

      <div class="stat-strip">
        <div class="stat-cell">
          <div class="lbl">${esc(T('totalRevenue', locale))}</div>
          <div class="val">${esc(fmtCur(r.total))}</div>
        </div>
        <div class="stat-cell">
          <div class="lbl">${esc(T('avgDaily', locale))}</div>
          <div class="val">${esc(fmtCur(r.avgDaily))}</div>
        </div>
        <div class="stat-cell">
          <div class="lbl">${esc(T('bestDay', locale))}</div>
          <div class="val">${r.bestDay ? esc(fmtCur(r.bestDay.amount)) : '—'}</div>
        </div>
        <div class="stat-cell">
          <div class="lbl">${esc(T('vsLastWeek', locale))}</div>
          <div class="val" style="color: ${k.mrr.deltaPct >= 0 ? '#06A87E' : '#FF3D5A'};">${esc(fmtPct(k.mrr.deltaPct))}</div>
        </div>
      </div>

      <div class="t-caption mb-2" style="color: ${pal.textFaint};">${esc(T('topCustomers', locale))}</div>
      <table class="zyrix-table page-break-avoid">
        <tbody>${customerRows}</tbody>
      </table>

      ${footer({ merchantName: data.merchantName, generatedAt: new Date(), locale })}
    </div>
  `;
}

function renderCashPage(args: {
  data: WeeklyReportTemplateData; theme: Theme; locale: Locale;
  fmtCur: (n: number) => string;
}): string {
  const { data, theme, locale, fmtCur } = args;
  const pal = paletteOf(theme);
  const c = data.snapshot.cash;
  const k = data.snapshot.kpis;

  // Margin trend approximation: 4-week mock from current value (we only
  // have one window); render as a flat sparkline placeholder.
  const marginTrend = [
    Math.max(0, k.margin.value - k.margin.delta * 3),
    Math.max(0, k.margin.value - k.margin.delta * 2),
    Math.max(0, k.margin.value - k.margin.delta),
    Math.max(0, k.margin.value)
  ];

  const expenseRows = c.topExpenses.length > 0
    ? c.topExpenses.map((e) => `
        <tr>
          <td>${esc(e.category)}</td>
          <td style="color: ${pal.textFaint}; font-size: 9pt;">${esc(e.date)}</td>
          <td style="text-align: right; font-weight: 700; color: #FF3D5A;">${esc(fmtCur(e.amount))}</td>
        </tr>`).join('')
    : `<tr><td colspan="3" style="text-align: center; color: ${pal.textFaint}; padding: 16pt;">${esc(T('noExpenses', locale))}</td></tr>`;

  return `
    <div class="section-page">
      <div class="section-title-row">
        <div>
          <div class="t-caption" style="color: ${pal.textFaint};">${esc(T('weeklyTitle', locale))}</div>
          <div class="t-display-md" style="margin-top: 4pt;">${esc(T('cashMargin', locale))}</div>
        </div>
      </div>

      <div class="page-break-avoid" style="margin-bottom: 14pt;">
        ${flowStream({
          inflows:  [{ name: T('inflows',  locale), value: c.inflowTotal  }],
          outflows: [{ name: T('outflows', locale), value: c.outflowTotal }],
          width: 520, height: 180, theme
        })}
      </div>

      <div class="stat-strip" style="grid-template-columns: repeat(3, 1fr);">
        <div class="stat-cell">
          <div class="lbl">${esc(T('inflows', locale))}</div>
          <div class="val" style="color: #06A87E;">${esc(fmtCur(c.inflowTotal))}</div>
        </div>
        <div class="stat-cell">
          <div class="lbl">${esc(T('outflows', locale))}</div>
          <div class="val" style="color: #FF3D5A;">${esc(fmtCur(c.outflowTotal))}</div>
        </div>
        <div class="stat-cell">
          <div class="lbl">${esc(T('netFlow', locale))}</div>
          <div class="val" style="color: ${c.netFlow >= 0 ? '#06A87E' : '#FF3D5A'};">${esc(fmtCur(c.netFlow))}</div>
        </div>
      </div>

      <div class="page-break-avoid" style="margin-bottom: 14pt;">
        <div class="t-caption mb-2" style="color: ${pal.textFaint};">${esc(T('margin', locale))}</div>
        ${pulseSparkline({ data: marginTrend, severity: 'normal', width: 240, height: 60, theme })}
      </div>

      <div class="t-caption mb-2" style="color: ${pal.textFaint};">${esc(T('topExpenses', locale))}</div>
      <table class="zyrix-table page-break-avoid">
        <tbody>${expenseRows}</tbody>
      </table>

      ${footer({ merchantName: data.merchantName, generatedAt: new Date(), locale })}
    </div>
  `;
}

function renderCustomerTaxPage(args: {
  data: WeeklyReportTemplateData; theme: Theme; locale: Locale;
  fmtCur: (n: number) => string;
}): string {
  const { data, theme, locale, fmtCur } = args;
  const pal = paletteOf(theme);
  const c = data.snapshot.customers;
  const tax = data.snapshot.tax;
  const tones: Tone[] = ['cyan', 'violet', 'mint', 'amber', 'crimson'];

  const concentrationData = c.concentration.slice(0, 5).map((s, i) => ({
    name:  s.name,
    value: s.amount,
    tone:  tones[i % tones.length]
  }));

  const concentrationRiskBlock = c.topCustomerShare > 40
    ? `<div style="background: rgba(255, 61, 90, 0.08); border: 1px solid rgba(255, 61, 90, 0.30);
                   border-radius: 10pt; padding: 12pt 14pt; margin-bottom: 14pt;">
        <div style="font-size: 9pt; font-weight: 700; color: #FF3D5A; text-transform: uppercase; letter-spacing: 0.08em;">
          ${esc(T('concentrationRisk', locale))}
        </div>
        <div style="margin-top: 4pt; font-size: 10pt; color: ${pal.textPrimary};">
          ${esc(c.concentration[0]?.name || '—')} — ${c.topCustomerShare.toFixed(1)}%
        </div>
      </div>`
    : '';

  const taxRows = tax.upcoming.length > 0
    ? tax.upcoming.map((t) => `
        <tr>
          <td>${esc(t.title)}</td>
          <td style="color: ${pal.textFaint}; font-size: 9pt;">${esc(t.dueDate)}</td>
          <td style="text-align: right; font-weight: 700;">${esc(fmtCur(t.amount))}</td>
        </tr>`).join('')
    : `<tr><td colspan="3" style="text-align: center; color: ${pal.textFaint}; padding: 16pt;">${esc(T('noTax', locale))}</td></tr>`;

  return `
    <div class="section-page">
      <div class="section-title-row">
        <div>
          <div class="t-caption" style="color: ${pal.textFaint};">${esc(T('weeklyTitle', locale))}</div>
          <div class="t-display-md" style="margin-top: 4pt;">${esc(T('customerTax', locale))}</div>
        </div>
      </div>

      ${concentrationData.length > 0 ? `
        <div style="display: flex; gap: 24pt; align-items: flex-start; margin-bottom: 16pt;">
          <div style="flex-shrink: 0;">
            ${holographicDonut({
              data: concentrationData,
              width: 200, height: 200, thickness: 26,
              centerSub: T('concentration', locale),
              format: fmtCur,
              theme
            })}
          </div>
          <div style="flex: 1;">
            ${concentrationRiskBlock}
            <table class="zyrix-table">
              <tbody>
                ${concentrationData.map((s) => `
                  <tr>
                    <td><span style="display: inline-block; width: 6pt; height: 6pt; border-radius: 50%; background: ${toneColor(s.tone)}; margin-${locale === 'ar' ? 'left' : 'right'}: 6pt;"></span>${esc(s.name)}</td>
                    <td style="text-align: right;">${esc(fmtCur(s.value))}</td>
                  </tr>`).join('')}
              </tbody>
            </table>
          </div>
        </div>
      ` : ''}

      <div class="t-caption mb-2" style="color: ${pal.textFaint};">${esc(T('upcomingTax', locale))}</div>
      <table class="zyrix-table page-break-avoid">
        <tbody>${taxRows}</tbody>
      </table>

      ${footer({ merchantName: data.merchantName, generatedAt: new Date(), locale })}
    </div>
  `;
}

function renderActionsPage(args: {
  data: WeeklyReportTemplateData; theme: Theme; locale: Locale;
}): string {
  const { data, theme, locale } = args;
  const pal = paletteOf(theme);

  const actions = data.insights.slice(0, 3);
  const list = actions.length > 0
    ? actions.map((i, idx) => `
        <div class="card page-break-avoid" style="margin-bottom: 12pt; display: flex; gap: 14pt; align-items: flex-start;">
          <div style="flex-shrink: 0; width: 28pt; height: 28pt; border-radius: 50%;
                      display: flex; align-items: center; justify-content: center;
                      background: rgba(157, 78, 221, 0.12); color: #9D4EDD;
                      font-size: 13pt; font-weight: 800;">${idx + 1}</div>
          <div style="flex: 1;">
            <div style="font-size: 8pt; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase;
                        color: ${i.type === 'CRITICAL' ? '#FF3D5A' : i.type === 'ATTENTION' ? '#FFB800' : '#06A87E'};">
              ${esc(T(i.type, locale))}
            </div>
            <div style="margin-top: 4pt; font-size: 12pt; font-weight: 700; color: ${pal.textPrimary};">
              ${esc(i.title)}
            </div>
            <div style="margin-top: 6pt; font-size: 10pt; line-height: 1.5; color: ${pal.textDim};">
              ${esc(i.body)}
            </div>
          </div>
        </div>`).join('')
    : `<div class="card" style="text-align: center; padding: 24pt; color: ${pal.textFaint}; font-size: 10pt;">${esc(T('noInsights', locale))}</div>`;

  return `
    <div class="section-page">
      <div class="section-title-row">
        <div>
          <div class="t-caption" style="color: ${pal.textFaint};">${esc(T('weeklyTitle', locale))}</div>
          <div class="t-display-md" style="margin-top: 4pt;">${esc(T('actions', locale))}</div>
        </div>
      </div>

      ${list}

      <div style="margin-top: 32pt; padding: 20pt; text-align: center;
                  background: linear-gradient(135deg, rgba(157, 78, 221, 0.08), rgba(0, 217, 255, 0.06));
                  border: 1px solid rgba(157, 78, 221, 0.25);
                  border-radius: 12pt;">
        <div style="font-size: 16pt; font-weight: 700; color: ${pal.textPrimary}; letter-spacing: -0.01em;">
          ${esc(T('closing', locale))}
        </div>
        <div style="margin-top: 8pt; font-size: 9pt; color: ${pal.textFaint};">
          Zyrix <span style="color: #00D9FF; font-weight: 700;">FinSuite</span> · finsuite.zyrix.co
        </div>
      </div>

      ${footer({ merchantName: data.merchantName, generatedAt: new Date(), locale })}
    </div>
  `;
}

function renderFoundationPage(data: WeeklyReportTemplateData, theme: Theme, locale: Locale): string {
  const pal = paletteOf(theme);
  return `
    <div style="padding: 60pt 32pt; text-align: center;">
      <div style="display: inline-flex; align-items: center; gap: 6pt;
                  padding: 6pt 14pt;
                  background: rgba(255, 184, 0, 0.10);
                  border: 1px solid rgba(255, 184, 0, 0.40);
                  border-radius: 99pt;
                  color: #FFB800;
                  font-size: 9pt; font-weight: 700; letter-spacing: 0.10em;
                  text-transform: uppercase;">
        ${esc(T('weeklyTitle', locale))}
      </div>
      <div style="margin-top: 24pt; font-size: 32pt; font-weight: 700; color: ${pal.textPrimary}; letter-spacing: -0.02em;">
        ${esc(T('foundationTitle', locale))}
      </div>
      <div style="margin-top: 18pt; font-size: 12pt; color: ${pal.textDim}; line-height: 1.7; max-width: 460pt; margin-inline: auto;">
        ${esc(T('foundationBody', locale))}
      </div>
      <div style="margin-top: 48pt; font-size: 9pt; color: ${pal.textFaint};">
        Zyrix <span style="color: #00D9FF; font-weight: 700;">FinSuite</span> · ${esc(formatDate(data.weekStart, locale))} — ${esc(formatDate(data.weekEnd, locale))}
      </div>
    </div>
  `;
}
