// ============================================================
// Zyrix FinSuite - e-Irsaliye XML Generator
// Sprint 1 Phase 1A
//
// Builds a UBL-TR 2.1 conformant XML payload for an e-Irsaliye
// (Turkish electronic waybill / despatch advice).
//
// Spec reference: GIB e-Belge UBL-TR 2.1, e-Irsaliye paketi.
// We emit the document hand-built (no XML library) to keep the
// dependency surface minimal and the output byte-identical
// to what the existing e-Fatura pipeline produces.
//
// Note: this module produces the raw XML only. Submission to
// GIB and digital signing are intentionally NOT included here -
// they depend on a GIB integrator account which is not yet
// provisioned. The status flow stops at SENT_PENDING_GIB.
// ============================================================

export type EIrsaliyeLineItem = {
  productCode?: string;       // optional internal/sku code
  description: string;        // mandatory: line description
  quantity: number;           // mandatory: numeric quantity
  unitCode?: string;          // UBL unit code, default "C62" (piece)
  unitPrice?: number;         // optional: 0 for non-priced waybills
  vatRate?: number;           // 0..1, e.g. 0.18 for 18%
  notes?: string;             // line-level note
};

export type EIrsaliyeXmlInput = {
  // Identification
  irsaliyeNo: string;         // e.g. "ZRX2026000000123"
  uuid: string;               // RFC 4122 UUID, generated by caller
  issueDate: Date;            // when the document is issued
  issueTime?: Date;           // optional separate time, default = issueDate

  // Sender (the merchant)
  sender: {
    vkn: string;              // 10 or 11 digit tax number
    title: string;            // legal company name
    address?: string;
    city?: string;
    country?: string;         // default "Turkiye"
    taxOffice?: string;
    phone?: string;
    email?: string;
  };

  // Receiver (the buyer / consignee)
  receiver: {
    vkn?: string;
    title: string;
    address?: string;
    city?: string;
    country?: string;
  };

  // Logistics
  delivery: {
    address?: string;         // physical delivery address
    deliveryDate?: Date;      // when goods are dispatched
    vehiclePlate?: string;
    driverName?: string;
    driverTcKimlik?: string;  // 11-digit Turkish ID
  };

  // Lines
  items: EIrsaliyeLineItem[];

  // Totals
  currency?: string;          // default "TRY"
  notes?: string;             // document-level notes
};

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

function escapeXml(value: unknown): string {
  if (value === null || value === undefined) return "";
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function isoDate(d: Date): string {
  // YYYY-MM-DD
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = String(d.getUTCDate()).padStart(2, "0");
  return y + "-" + m + "-" + day;
}

function isoTime(d: Date): string {
  // HH:mm:ss
  const h = String(d.getUTCHours()).padStart(2, "0");
  const m = String(d.getUTCMinutes()).padStart(2, "0");
  const s = String(d.getUTCSeconds()).padStart(2, "0");
  return h + ":" + m + ":" + s;
}

function fmtAmount(n: number): string {
  // 2 decimal places, dot separator, no thousands separator
  if (!isFinite(n)) return "0.00";
  return n.toFixed(2);
}

function fmtQty(n: number): string {
  if (!isFinite(n)) return "0";
  // up to 6 decimals, drop trailing zeros
  const s = n.toFixed(6);
  return s.replace(/0+$/, "").replace(/\.$/, "");
}

// Compute line total = qty * unitPrice
function lineTotal(item: EIrsaliyeLineItem): number {
  const q = Number(item.quantity || 0);
  const p = Number(item.unitPrice || 0);
  return q * p;
}

// Compute line VAT = lineTotal * vatRate
function lineVat(item: EIrsaliyeLineItem): number {
  const total = lineTotal(item);
  const rate = Number(item.vatRate || 0);
  return total * rate;
}

// ----------------------------------------------------------------
// XML builder
// ----------------------------------------------------------------

const UBL_HEADER = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<DespatchAdvice xmlns="urn:oasis:names:specification:ubl:schema:xsd:DespatchAdvice-2"',
  '                xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"',
  '                xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"',
  '                xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"',
  '                xmlns:ds="http://www.w3.org/2000/09/xmldsig#"',
  '                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">',
].join("\n");

function buildExtensions(): string {
  // Empty extension placeholder. Signatures are added by the
  // signing pipeline (not in scope here).
  return [
    "  <ext:UBLExtensions>",
    "    <ext:UBLExtension>",
    "      <ext:ExtensionContent />",
    "    </ext:UBLExtension>",
    "  </ext:UBLExtensions>",
  ].join("\n");
}

function buildHeader(input: EIrsaliyeXmlInput): string {
  const issue = input.issueDate;
  const time = input.issueTime || issue;
  return [
    '  <cbc:UBLVersionID>2.1</cbc:UBLVersionID>',
    '  <cbc:CustomizationID>TR1.2</cbc:CustomizationID>',
    '  <cbc:ProfileID>TEMELIRSALIYE</cbc:ProfileID>',
    '  <cbc:ID>' + escapeXml(input.irsaliyeNo) + '</cbc:ID>',
    '  <cbc:UUID>' + escapeXml(input.uuid) + '</cbc:UUID>',
    '  <cbc:IssueDate>' + isoDate(issue) + '</cbc:IssueDate>',
    '  <cbc:IssueTime>' + isoTime(time) + '</cbc:IssueTime>',
    '  <cbc:DespatchAdviceTypeCode>SEVK</cbc:DespatchAdviceTypeCode>',
    input.notes
      ? '  <cbc:Note>' + escapeXml(input.notes) + '</cbc:Note>'
      : '',
  ]
    .filter(Boolean)
    .join("\n");
}

function buildSenderParty(input: EIrsaliyeXmlInput): string {
  const s = input.sender;
  const country = s.country || "Turkiye";
  return [
    '  <cac:DespatchSupplierParty>',
    '    <cac:Party>',
    '      <cac:PartyIdentification>',
    '        <cbc:ID schemeID="VKN">' + escapeXml(s.vkn) + '</cbc:ID>',
    '      </cac:PartyIdentification>',
    '      <cac:PartyName>',
    '        <cbc:Name>' + escapeXml(s.title) + '</cbc:Name>',
    '      </cac:PartyName>',
    '      <cac:PostalAddress>',
    s.address ? '        <cbc:StreetName>' + escapeXml(s.address) + '</cbc:StreetName>' : '',
    s.city    ? '        <cbc:CityName>' + escapeXml(s.city) + '</cbc:CityName>' : '',
    '        <cac:Country>',
    '          <cbc:Name>' + escapeXml(country) + '</cbc:Name>',
    '        </cac:Country>',
    '      </cac:PostalAddress>',
    s.taxOffice
      ? [
          '      <cac:PartyTaxScheme>',
          '        <cac:TaxScheme>',
          '          <cbc:Name>' + escapeXml(s.taxOffice) + '</cbc:Name>',
          '        </cac:TaxScheme>',
          '      </cac:PartyTaxScheme>',
        ].join("\n")
      : '',
    s.phone || s.email
      ? [
          '      <cac:Contact>',
          s.phone ? '        <cbc:Telephone>' + escapeXml(s.phone) + '</cbc:Telephone>' : '',
          s.email ? '        <cbc:ElectronicMail>' + escapeXml(s.email) + '</cbc:ElectronicMail>' : '',
          '      </cac:Contact>',
        ].filter(Boolean).join("\n")
      : '',
    '    </cac:Party>',
    '  </cac:DespatchSupplierParty>',
  ]
    .filter(Boolean)
    .join("\n");
}

function buildReceiverParty(input: EIrsaliyeXmlInput): string {
  const r = input.receiver;
  const country = r.country || "Turkiye";
  return [
    '  <cac:DeliveryCustomerParty>',
    '    <cac:Party>',
    r.vkn
      ? [
          '      <cac:PartyIdentification>',
          '        <cbc:ID schemeID="VKN">' + escapeXml(r.vkn) + '</cbc:ID>',
          '      </cac:PartyIdentification>',
        ].join("\n")
      : '',
    '      <cac:PartyName>',
    '        <cbc:Name>' + escapeXml(r.title) + '</cbc:Name>',
    '      </cac:PartyName>',
    '      <cac:PostalAddress>',
    r.address ? '        <cbc:StreetName>' + escapeXml(r.address) + '</cbc:StreetName>' : '',
    r.city    ? '        <cbc:CityName>' + escapeXml(r.city) + '</cbc:CityName>' : '',
    '        <cac:Country>',
    '          <cbc:Name>' + escapeXml(country) + '</cbc:Name>',
    '        </cac:Country>',
    '      </cac:PostalAddress>',
    '    </cac:Party>',
    '  </cac:DeliveryCustomerParty>',
  ]
    .filter(Boolean)
    .join("\n");
}

function buildShipment(input: EIrsaliyeXmlInput): string {
  const d = input.delivery;
  // Shipment is required even if mostly empty
  const lines: string[] = [
    '  <cac:Shipment>',
    '    <cbc:ID>1</cbc:ID>',
  ];

  // Delivery date
  if (d.deliveryDate) {
    lines.push('    <cac:Delivery>');
    lines.push('      <cbc:ActualDeliveryDate>' + isoDate(d.deliveryDate) + '</cbc:ActualDeliveryDate>');
    if (d.address) {
      lines.push('      <cac:DeliveryAddress>');
      lines.push('        <cbc:StreetName>' + escapeXml(d.address) + '</cbc:StreetName>');
      lines.push('        <cac:Country>');
      lines.push('          <cbc:Name>Turkiye</cbc:Name>');
      lines.push('        </cac:Country>');
      lines.push('      </cac:DeliveryAddress>');
    }
    lines.push('    </cac:Delivery>');
  } else if (d.address) {
    // Address only, no date
    lines.push('    <cac:Delivery>');
    lines.push('      <cac:DeliveryAddress>');
    lines.push('        <cbc:StreetName>' + escapeXml(d.address) + '</cbc:StreetName>');
    lines.push('        <cac:Country>');
    lines.push('          <cbc:Name>Turkiye</cbc:Name>');
    lines.push('        </cac:Country>');
    lines.push('      </cac:DeliveryAddress>');
    lines.push('    </cac:Delivery>');
  }

  // Vehicle / driver info
  if (d.vehiclePlate || d.driverName || d.driverTcKimlik) {
    lines.push('    <cac:ShipmentStage>');
    if (d.vehiclePlate) {
      lines.push('      <cac:TransportMeans>');
      lines.push('        <cac:RoadTransport>');
      lines.push('          <cbc:LicensePlateID>' + escapeXml(d.vehiclePlate) + '</cbc:LicensePlateID>');
      lines.push('        </cac:RoadTransport>');
      lines.push('      </cac:TransportMeans>');
    }
    if (d.driverName || d.driverTcKimlik) {
      lines.push('      <cac:DriverPerson>');
      if (d.driverName) {
        lines.push('        <cbc:FirstName>' + escapeXml(d.driverName) + '</cbc:FirstName>');
      }
      if (d.driverTcKimlik) {
        lines.push('        <cbc:NationalityID>' + escapeXml(d.driverTcKimlik) + '</cbc:NationalityID>');
      }
      lines.push('      </cac:DriverPerson>');
    }
    lines.push('    </cac:ShipmentStage>');
  }

  lines.push('  </cac:Shipment>');
  return lines.join("\n");
}

function buildLine(item: EIrsaliyeLineItem, index: number, currency: string): string {
  const qty = Number(item.quantity || 0);
  const total = lineTotal(item);
  const unitCode = item.unitCode || "C62";
  return [
    '  <cac:DespatchLine>',
    '    <cbc:ID>' + (index + 1) + '</cbc:ID>',
    '    <cbc:DeliveredQuantity unitCode="' + escapeXml(unitCode) + '">' + fmtQty(qty) + '</cbc:DeliveredQuantity>',
    item.unitPrice !== undefined && item.unitPrice !== null
      ? '    <cbc:LineExtensionAmount currencyID="' + escapeXml(currency) + '">' + fmtAmount(total) + '</cbc:LineExtensionAmount>'
      : '',
    item.notes
      ? '    <cbc:Note>' + escapeXml(item.notes) + '</cbc:Note>'
      : '',
    '    <cac:Item>',
    '      <cbc:Name>' + escapeXml(item.description) + '</cbc:Name>',
    item.productCode
      ? [
          '      <cac:SellersItemIdentification>',
          '        <cbc:ID>' + escapeXml(item.productCode) + '</cbc:ID>',
          '      </cac:SellersItemIdentification>',
        ].join("\n")
      : '',
    '    </cac:Item>',
    item.unitPrice !== undefined && item.unitPrice !== null
      ? [
          '    <cac:Price>',
          '      <cbc:PriceAmount currencyID="' + escapeXml(currency) + '">' + fmtAmount(Number(item.unitPrice || 0)) + '</cbc:PriceAmount>',
          '    </cac:Price>',
        ].join("\n")
      : '',
    '  </cac:DespatchLine>',
  ]
    .filter(Boolean)
    .join("\n");
}

// ----------------------------------------------------------------
// Public entrypoint
// ----------------------------------------------------------------

export function buildEIrsaliyeXml(input: EIrsaliyeXmlInput): string {
  if (!input.irsaliyeNo) throw new Error("irsaliyeNo is required");
  if (!input.uuid) throw new Error("uuid is required");
  if (!input.sender || !input.sender.vkn || !input.sender.title) {
    throw new Error("sender.vkn and sender.title are required");
  }
  if (!input.receiver || !input.receiver.title) {
    throw new Error("receiver.title is required");
  }
  if (!Array.isArray(input.items) || input.items.length === 0) {
    throw new Error("at least one line item is required");
  }

  const currency = input.currency || "TRY";

  const parts: string[] = [
    UBL_HEADER,
    buildExtensions(),
    buildHeader(input),
    buildSenderParty(input),
    buildReceiverParty(input),
    buildShipment(input),
  ];

  input.items.forEach((it, idx) => {
    parts.push(buildLine(it, idx, currency));
  });

  parts.push("</DespatchAdvice>");
  return parts.join("\n");
}

// ----------------------------------------------------------------
// Compute totals (used by the controller for persistence)
// ----------------------------------------------------------------

export function computeTotals(items: EIrsaliyeLineItem[]) {
  let subtotal = 0;
  let vatTotal = 0;
  for (const it of items) {
    subtotal += lineTotal(it);
    vatTotal += lineVat(it);
  }
  const grand = subtotal + vatTotal;
  return {
    subtotal: Number(subtotal.toFixed(2)),
    vatTotal: Number(vatTotal.toFixed(2)),
    grandTotal: Number(grand.toFixed(2)),
  };
}
