// ================================================================
// shareEmailTemplate.ts — branded HTML for share emails.
// Inline strings to match the existing emailService.ts pattern;
// no @react-email dependency. Three locales (tr/ar/en); RTL handled
// via dir="rtl" on the html tag. The PDF rides as a base64 attachment
// (option δ from the discovery doc), so this template carries an
// "attached" indicator rather than a download link.
// ================================================================
import type { Locale } from "../pdf/palette";

type Severity = "critical" | "attention" | "opportunity";

const STR = {
  // Header / labels
  appName:   { tr: "Zyrix FinSuite",      en: "Zyrix FinSuite",      ar: "زايريكس فينسوت" },
  copilot:   { tr: "AI Co-Pilot",         en: "AI Co-Pilot",         ar: "المساعد الذكي" },
  sharedBy:  { tr: "{name} sizinle paylaştı", en: "{name} shared this with you", ar: "شارك معك {name}" },
  attached:  { tr: "PDF eklendi",         en: "PDF attached",        ar: "تم إرفاق ملف PDF" },
  poweredBy: { tr: "Zyrix FinSuite tarafından oluşturuldu", en: "Generated by Zyrix FinSuite", ar: "تم إنشاؤه بواسطة زايريكس" },
  visit:     { tr: "FinSuite'i keşfet",   en: "Explore FinSuite",    ar: "اكتشف FinSuite" },
  // Severity badges (mirror D-2 PDF chrome)
  critical:    { tr: "KRİTİK",     en: "CRITICAL",     ar: "حرج" },
  attention:   { tr: "DİKKAT",     en: "ATTENTION",    ar: "تنبيه" },
  opportunity: { tr: "FIRSAT",     en: "OPPORTUNITY",  ar: "فرصة" },
  // Document type labels
  insightLabel:    { tr: "AI İçgörü",        en: "AI Insight",        ar: "رؤية ذكاء اصطناعي" },
  dailyBriefLabel: { tr: "Günlük Brifing",   en: "Daily Brief",       ar: "الإيجاز اليومي" },
  rangeLabel:      { tr: "Performans Raporu", en: "Performance Report", ar: "تقرير الأداء" }
} as const;

const T = (key: keyof typeof STR, locale: Locale): string =>
  STR[key]?.[locale] || STR[key]?.tr || String(key);

const SEVERITY_TONE: Record<Severity, { color: string; bg: string; border: string }> = {
  critical:    { color: "#FF3D5A", bg: "rgba(255, 61, 90, 0.08)",  border: "rgba(255, 61, 90, 0.32)"  },
  attention:   { color: "#FFB800", bg: "rgba(255, 184, 0, 0.08)",  border: "rgba(255, 184, 0, 0.32)"  },
  opportunity: { color: "#06A87E", bg: "rgba(6, 168, 126, 0.08)",  border: "rgba(6, 168, 126, 0.32)"  }
};

/** HTML escape for safe interpolation. */
function esc(s: unknown): string {
  if (s === null || s === undefined) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export interface ShareEmailArgs {
  /** Sender (the merchant doing the sharing). */
  senderName:    string;
  /** Optional custom note typed by the merchant. */
  customMessage?: string;
  /** What's being shared. */
  document: {
    type:        "single_insight" | "daily_brief" | "range_report";
    title:       string;        // "Bugünün Brifingi: Demir Tekstil — 9 Mayıs 2026"
    severity?:   Severity;      // only for single_insight
    body?:       string;        // optional preview body (1-2 sentences)
    badge?:      string;        // pre-localized severity / doc-type label
  };
  /** PDF attached as base64 — surfaced in the body as a chip. */
  pdfFilename?:  string;
  pdfSizeBytes?: number;
  locale:        Locale;
}

export function buildShareEmailSubject(args: ShareEmailArgs): string {
  const docName =
    args.document.type === "single_insight"  ? T("insightLabel",    args.locale)
  : args.document.type === "daily_brief"     ? T("dailyBriefLabel", args.locale)
                                              : T("rangeLabel",      args.locale);
  return `${docName} · ${args.document.title}`;
}

export function buildShareEmailHtml(args: ShareEmailArgs): string {
  const { senderName, customMessage, document, pdfFilename, pdfSizeBytes, locale } = args;
  const dir = locale === "ar" ? "rtl" : "ltr";
  const fontStack = locale === "ar"
    ? "'IBM Plex Sans Arabic', 'Inter', system-ui, sans-serif"
    : "'Inter', 'Segoe UI', system-ui, sans-serif";
  const align = locale === "ar" ? "right" : "left";

  const sev = document.severity ? SEVERITY_TONE[document.severity] : null;
  const badge = document.badge
    ? document.badge
    : document.severity ? T(document.severity, locale)
    : document.type === "daily_brief" ? T("dailyBriefLabel", locale)
    : document.type === "range_report" ? T("rangeLabel", locale)
                                       : T("insightLabel", locale);

  const sharedByLine = T("sharedBy", locale).replace("{name}", esc(senderName));
  const sizeKb = pdfSizeBytes ? Math.max(1, Math.round(pdfSizeBytes / 1024)) : null;

  return `<!DOCTYPE html>
<html lang="${esc(locale)}" dir="${dir}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${esc(buildShareEmailSubject(args))}</title>
</head>
<body style="margin:0; padding:0; background:#F0F4FF; font-family:${fontStack}; -webkit-font-smoothing:antialiased;">
  <div style="max-width:600px; margin:24px auto; background:#FFFFFF; border-radius:18px; overflow:hidden; box-shadow:0 4px 32px rgba(15, 23, 42, 0.08); text-align:${align};">

    <!-- HEADER (cinematic gradient mesh as solid CSS-radial) -->
    <div style="background:radial-gradient(ellipse 70% 60% at 30% 30%, rgba(157, 78, 221, 0.85), transparent 60%), radial-gradient(ellipse 70% 60% at 70% 60%, rgba(0, 217, 255, 0.85), transparent 60%), linear-gradient(135deg, #0A0E27 0%, #131838 100%); padding:32px 36px 28px; position:relative;">
      <div style="display:inline-flex; align-items:center; gap:8px; padding:6px 12px; background:rgba(0, 217, 255, 0.12); border:1px solid rgba(0, 217, 255, 0.40); border-radius:999px; color:#5DFAFF; font-size:10px; font-weight:700; letter-spacing:0.10em; text-transform:uppercase;">
        <span style="display:inline-block; width:6px; height:6px; border-radius:50%; background:#5DFAFF;"></span>
        ${esc(T("appName", locale))} · ${esc(T("copilot", locale))}
      </div>
      <h1 style="margin:18px 0 0; color:#F8FAFC; font-size:22px; font-weight:700; letter-spacing:-0.02em; line-height:1.25;">
        ${esc(document.title)}
      </h1>
      <p style="margin:8px 0 0; color:#CBD5E1; font-size:13px;">
        ${sharedByLine}
      </p>
    </div>

    <!-- BODY -->
    <div style="padding:28px 36px;">

      ${sev ? `
      <div style="display:inline-flex; align-items:center; gap:6px; padding:4px 10px; margin-bottom:14px; background:${sev.bg}; border:1px solid ${sev.border}; border-radius:999px; color:${sev.color}; font-size:11px; font-weight:700; letter-spacing:0.08em; text-transform:uppercase;">
        <span style="display:inline-block; width:6px; height:6px; border-radius:50%; background:${sev.color};"></span>
        ${esc(badge)}
      </div>` : `
      <div style="display:inline-flex; align-items:center; gap:6px; padding:4px 10px; margin-bottom:14px; background:rgba(0, 217, 255, 0.08); border:1px solid rgba(0, 217, 255, 0.30); border-radius:999px; color:#0078A8; font-size:11px; font-weight:700; letter-spacing:0.08em; text-transform:uppercase;">
        ${esc(badge)}
      </div>`}

      ${document.body ? `
      <div style="background:#F8FAFF; border:1px solid rgba(15, 23, 42, 0.06); border-radius:14px; padding:16px 18px; margin-bottom:18px;">
        <div style="font-size:14.5px; line-height:1.55; color:#0F172A;">${esc(document.body)}</div>
      </div>` : ``}

      ${customMessage ? `
      <div style="border-${align === "right" ? "right" : "left"}:3px solid #9D4EDD; padding:8px 14px; margin:0 0 18px; color:#475569; font-size:14px; line-height:1.55; font-style:italic;">
        ${esc(customMessage)}
      </div>` : ``}

      ${pdfFilename ? `
      <div style="display:flex; align-items:center; gap:12px; padding:12px 14px; background:#F0F4FF; border:1px solid rgba(108, 58, 255, 0.18); border-radius:12px; margin-bottom:20px;">
        <div style="width:36px; height:36px; border-radius:8px; display:inline-flex; align-items:center; justify-content:center; background:rgba(157, 78, 221, 0.12); color:#9D4EDD; font-size:18px; font-weight:800; flex-shrink:0;">📎</div>
        <div style="flex:1; min-width:0;">
          <div style="font-size:13px; font-weight:700; color:#0F172A;">${esc(pdfFilename)}</div>
          <div style="font-size:11px; color:#64748B; margin-top:2px;">${esc(T("attached", locale))}${sizeKb ? ` · ${sizeKb} KB` : ""}</div>
        </div>
      </div>` : ``}

      <!-- CTA -->
      <div style="text-align:center; margin-top:24px;">
        <a href="https://finsuite.zyrix.co" style="display:inline-block; background:linear-gradient(135deg, #9D4EDD 0%, #00D9FF 100%); color:#FFFFFF; text-decoration:none; border-radius:12px; padding:12px 28px; font-size:13px; font-weight:700; letter-spacing:0.04em; box-shadow:0 4px 18px rgba(157, 78, 221, 0.30);">
          ${esc(T("visit", locale))} →
        </a>
      </div>
    </div>

    <!-- FOOTER -->
    <div style="background:#F8FAFF; padding:18px 36px; border-top:1px solid rgba(15, 23, 42, 0.06); text-align:center;">
      <p style="margin:0; color:#94A3B8; font-size:11px; line-height:1.6;">
        ${esc(T("poweredBy", locale))}<br />
        <a href="https://finsuite.zyrix.co" style="color:#9D4EDD; text-decoration:none; font-weight:600;">finsuite.zyrix.co</a>
      </p>
    </div>
  </div>
</body>
</html>`;
}
