// ================================================================
// Sprint D-9 — Slack Block Kit renderer for insights + KPI replies.
//
// Decision §10.G option G1 — text-only blocks with severity emoji
// header, no PNG generation. Matches ~95% of the spec mock's visual
// impact via header text + mrkdwn weight; promote to G2 (D-7 OG-style
// PNG header) in V2 if Slack engagement metrics warrant the cost.
//
// Outputs the { text, blocks } shape consumed by chat.postMessage.
// `text` is the fallback for clients that strip blocks (notification
// previews, mobile shortcuts, archived workspaces). Always populate
// it — Slack downgrades to text-only when blocks fail to render.
// ================================================================

export type Locale = "tr" | "en" | "ar";

export type SlackBlock =
  | { type: "header";  text: { type: "plain_text"; text: string; emoji?: boolean } }
  | { type: "section"; text?: { type: "mrkdwn" | "plain_text"; text: string }; fields?: Array<{ type: "mrkdwn"; text: string }> }
  | { type: "context"; elements: Array<{ type: "mrkdwn" | "plain_text"; text: string }> }
  | { type: "divider" }
  | { type: "actions"; block_id?: string; elements: SlackButton[] };

export type SlackButton = {
  type:      "button";
  text:      { type: "plain_text"; text: string; emoji?: boolean };
  action_id: string;
  value?:    string;
  url?:      string;
  style?:    "primary" | "danger";
};

export interface InsightForSlack {
  id:           string;
  type:         "CRITICAL" | "ATTENTION" | "OPPORTUNITY";
  title:        string;
  body:         string;
  ctaLabel?:    string | null;
  ctaRoute?:    string | null;
  numericRefs?: unknown;
  generatedAt?: Date;
}

export interface RenderInsightArgs {
  insight:    InsightForSlack;
  locale:     Locale;
  /** Where the "View in FinSuite" button links to. */
  appBaseUrl: string;
}

// ─── Locale strings ──────────────────────────────────────────

interface Strings {
  badge:        Record<"CRITICAL" | "ATTENTION" | "OPPORTUNITY", string>;
  viewInApp:    string;
  resolve:      string;
  dismiss:      string;
  share:        string;
  footer:       string;
  testBanner:   string;
  ago:          (mins: number) => string;
}

const STRINGS: Record<Locale, Strings> = {
  tr: {
    badge: { CRITICAL: "🔴 KRİTİK", ATTENTION: "🟠 DİKKAT", OPPORTUNITY: "🟢 FIRSAT" },
    viewInApp:  "FinSuite'te Aç",
    resolve:    "Çözüldü olarak işaretle",
    dismiss:    "Yoksay",
    share:      "Başka kanala gönder",
    footer:     "Zyrix AI Co-Pilot tarafından oluşturuldu",
    testBanner: "🧪 Test mesajı — lütfen yoksayın",
    ago: (m) => m < 1 ? "az önce" : m < 60 ? `${m} dk önce` : `${Math.floor(m/60)} saat önce`
  },
  en: {
    badge: { CRITICAL: "🔴 CRITICAL", ATTENTION: "🟠 ATTENTION", OPPORTUNITY: "🟢 OPPORTUNITY" },
    viewInApp:  "Open in FinSuite",
    resolve:    "Mark as resolved",
    dismiss:    "Dismiss",
    share:      "Share to another channel",
    footer:     "Generated by Zyrix AI Co-Pilot",
    testBanner: "🧪 Test message — please ignore",
    ago: (m) => m < 1 ? "just now" : m < 60 ? `${m} min ago` : `${Math.floor(m/60)} hr ago`
  },
  ar: {
    badge: { CRITICAL: "🔴 حرج", ATTENTION: "🟠 انتباه", OPPORTUNITY: "🟢 فرصة" },
    viewInApp:  "افتح في FinSuite",
    resolve:    "وضع كمحلول",
    dismiss:    "تجاهل",
    share:      "مشاركة في قناة أخرى",
    footer:     "تم إنشاؤه بواسطة Zyrix AI Co-Pilot",
    testBanner: "🧪 رسالة اختبار — يرجى تجاهلها",
    ago: (m) => m < 1 ? "الآن" : m < 60 ? `قبل ${m} د` : `قبل ${Math.floor(m/60)} س`
  }
};

// ─── Numeric refs rendering ──────────────────────────────────

function renderNumericRefs(refs: unknown): Array<{ type: "mrkdwn"; text: string }> {
  if (!refs || typeof refs !== "object") return [];
  const fields: Array<{ type: "mrkdwn"; text: string }> = [];
  for (const [key, value] of Object.entries(refs as Record<string, unknown>)) {
    if (value === null || value === undefined) continue;
    // Slack hard-caps fields at 10; keep it lean.
    if (fields.length >= 6) break;
    const label = key.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase());
    fields.push({ type: "mrkdwn", text: `*${label}:*\n${String(value)}` });
  }
  return fields;
}

// ─── Renderers ───────────────────────────────────────────────

export function renderInsightAsBlocks(args: RenderInsightArgs): { text: string; blocks: SlackBlock[] } {
  const { insight, locale, appBaseUrl } = args;
  const s = STRINGS[locale] || STRINGS.tr;
  const badge = s.badge[insight.type] || insight.type;

  const minsAgo = insight.generatedAt
    ? Math.max(0, Math.floor((Date.now() - new Date(insight.generatedAt).getTime()) / 60000))
    : 0;

  const blocks: SlackBlock[] = [
    { type: "header",  text: { type: "plain_text", text: badge, emoji: true } },
    { type: "section", text: { type: "mrkdwn", text: `*${insight.title}*\n\n${insight.body}` } }
  ];

  const numericFields = renderNumericRefs(insight.numericRefs);
  if (numericFields.length > 0) {
    blocks.push({ type: "section", fields: numericFields });
  }

  const deepLink = `${appBaseUrl.replace(/\/$/, "")}${insight.ctaRoute || `/insights?id=${encodeURIComponent(insight.id)}`}`;
  const actions: SlackButton[] = [
    {
      type:      "button",
      text:      { type: "plain_text", text: insight.ctaLabel || s.viewInApp, emoji: true },
      action_id: `view:${insight.id}`,
      url:       deepLink,
      style:     "primary"
    },
    {
      type:      "button",
      text:      { type: "plain_text", text: s.resolve, emoji: true },
      action_id: `resolve:${insight.id}`,
      value:     insight.id,
      style:     "danger"
    },
    {
      type:      "button",
      text:      { type: "plain_text", text: s.share, emoji: true },
      action_id: `share:${insight.id}`,
      value:     insight.id
    }
  ];
  blocks.push({ type: "actions", block_id: `actions:${insight.id}`, elements: actions });

  blocks.push({
    type: "context",
    elements: [{
      type: "mrkdwn",
      text: `${s.ago(minsAgo)} • ${s.footer}`
    }]
  });

  // Plain-text fallback that always carries the gist (Slack notifications
  // and mobile peeks render this when blocks aren't supported).
  const text = `${badge} — ${insight.title}\n\n${insight.body}`;
  return { text, blocks };
}

// ─── Test-send wrapper ───────────────────────────────────────

export function renderTestMessageAsBlocks(args: { locale: Locale; workspaceName?: string }): { text: string; blocks: SlackBlock[] } {
  const s = STRINGS[args.locale] || STRINGS.tr;
  const blocks: SlackBlock[] = [
    { type: "header",  text: { type: "plain_text", text: s.testBanner, emoji: true } },
    { type: "section", text: { type: "mrkdwn", text: args.workspaceName ? `Slack ↔ FinSuite — *${args.workspaceName}*` : "Slack ↔ FinSuite" } },
    { type: "context", elements: [{ type: "mrkdwn", text: s.footer }] }
  ];
  return { text: s.testBanner, blocks };
}

// ─── Slash-command reply renderer ────────────────────────────

export interface KpiReplyArgs {
  locale:        Locale;
  title:         string;          // e.g. "Aylık Tekrarlayan Gelir (MRR)"
  primaryValue:  string;          // pre-formatted, e.g. "32.500 ₺"
  secondaryLine?: string;         // e.g. "Geçen aya göre %12 artış"
  fields?:       Array<{ label: string; value: string }>;
  appBaseUrl?:   string;
  ctaPath?:      string;          // optional "View in FinSuite" deep link
}

export function renderKpiReplyAsBlocks(args: KpiReplyArgs): { text: string; blocks: SlackBlock[] } {
  const s = STRINGS[args.locale] || STRINGS.tr;
  const blocks: SlackBlock[] = [
    { type: "header",  text: { type: "plain_text", text: args.title, emoji: true } },
    { type: "section", text: { type: "mrkdwn", text: `*${args.primaryValue}*${args.secondaryLine ? `\n_${args.secondaryLine}_` : ""}` } }
  ];

  if (args.fields && args.fields.length > 0) {
    blocks.push({
      type:   "section",
      fields: args.fields.slice(0, 6).map((f) => ({
        type: "mrkdwn",
        text: `*${f.label}:*\n${f.value}`
      }))
    });
  }

  if (args.appBaseUrl && args.ctaPath) {
    blocks.push({
      type: "actions",
      elements: [{
        type:      "button",
        text:      { type: "plain_text", text: s.viewInApp, emoji: true },
        action_id: `view:kpi:${args.ctaPath}`,
        url:       `${args.appBaseUrl.replace(/\/$/, "")}${args.ctaPath}`,
        style:     "primary"
      }]
    });
  }

  blocks.push({
    type: "context",
    elements: [{ type: "mrkdwn", text: s.footer }]
  });

  return { text: `${args.title} — ${args.primaryValue}`, blocks };
}
